### ISSUE TITLE
Fix support for EcmaScript modules

### ISSUE THREAD

**Issue by hussainweb** [hussainweb/drupalqa-action#10]
Some of the issues with using ESM were fixed in #8 (such as support in eslint and [jest](https://jestjs.io/docs/ecmascript-modules)). However, there is still an error with Github Actions which is likely due to ncc.

```
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/home/runner/work/_actions/hussainweb/drupalqa-action/main/dist/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at eval (eval at 433 (file:///home/runner/work/_actions/hussainweb/drupalqa-action/main/webpack:/drupalqa-action/node_modules/@vercel/ncc/dist/ncc/@@notfound.js:1:1), <anonymous>:1:1)
    at Object.433 (file:///home/runner/work/_actions/hussainweb/drupalqa-action/main/webpack:/drupalqa-action/node_modules/@vercel/ncc/dist/ncc/@@notfound.js:1:1)
    at __nccwpck_require__ (file:///home/runner/work/_actions/hussainweb/drupalqa-action/main/webpack:/drupalqa-action/webpack/bootstrap:21:1)
    at file:///home/runner/work/_actions/hussainweb/drupalqa-action/main/dist/index.js:9629:73
    at file:///home/runner/work/_actions/hussainweb/drupalqa-action/main/dist/index.js:9714:3
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at loadESM (node:internal/process/esm_loader:88:5)
    at handleMainPromise (node:internal/modules/run_main:65:12)
```

**Comment by hussainweb** [comment]
The problem _seems_ to be the fact that Github Actions libraries are written in TypeScript and compiled to use CommonJS. This means that many of the modules end up using `require` and possibly this is being left over after ncc compilation.

Instead of figuring out how to transpile that, it is probably better to just use TypeScript here. So, I'll revert the commit for now and create a new issue for TypeScript.
